name: Build AmneziaWG-Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      # Build the binary
      - name: Build AmneziaWG-Go
        run: |
          make

      # Upload the built artifact
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: amneziawg-go
          path: ./amneziawg-go
